server:
  port: 8081

spring:
  application:
    name: tjtechy-inventory-management-sept2024

  #datasource:
    #url: jdbc:h2:mem:tjtechy-inventory-management-sept2024
    #username: root
    #password: root
    #driver-class-name: com.mysql.cj.jdbc.Driver
  #jpa:
    #hibernate:
      #ddl-auto: update
    #show-sql: true
    #properties:
      #hibernate:
        #dialect: org.hibernate.dialect.MySQLDialect

      #format_sql: true
    #database: mysql
    #database-platform: org.hibernate.dialect.MySQL8Dialect

    datasource:
      url: jdbc:h2:mem:tjtechy-inventory-management-sept2024
      username: sa
      password:
    jpa:
      show-sql: true




api:
  endpoint:
    base-url: /api/v1






#logging.level.org.hibernate.SQL=DEBUG
#logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE