#here we define the profile that the application will run on, when started
#for example, I don't want any data manipulation or application inserting
#data from the DbInitializer into the msql database
#on start, the spring boot will check this file and load the application specific profile that is active
#if you start the application, the active profile will be shown in the console
server:
  port: 8081
spring:
  profiles:
    #active: h2-database
    #active: mysql-database
    active: postgres-database
  application:
    name: tjtechy-inventory-management-sept2024
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false

api:
  endpoint:
    base-url: /api/v1