scrape_configs:
  - job_name: "tjtechy-inventory-management-app"
    metrics_path: "/actuator/prometheus"
    scrape_interval: 3s #how often to scrap
    static_configs:
      - targets: ["host.docker.internal:8081"] #change to production host address, this is just for demo